services:
  app:
    build:
      context: .
    environment:
      GOMODCACHE: /go/src/.modcache
      GOCACHE: /go/src/.cache
    volumes:
      - "./:/go/src"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: blog
    volumes:
      - "./.service-db:/var/lib/mysql"
    ports:
      - "3333:3306"
